# Basic Python

## 1. Split this string

In [8]:
s = "Hi there Sam!"

In [17]:
for ch in "['()&]":
    s = s.replace(ch, '')


import re
s = re.sub(r"[]['()&]", "", s)
print(s)




Hi there Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
print ("The volume of the earth = ", '{:20,.2f}'.format(diameter), "Kms3\n\n")

The volume of the earth =             12,742.00 Kms3




## 3. In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
d['k1'][3]['tricky'][3]['target'][3]



'hello'

# Numpy

In [12]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [15]:
buckets = [0] * 10
print(buckets)




[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [18]:
import numpy as np

the_array = np.array([5]*3 + [0]*7)


the_array = np.zeros((10,))
the_array[:3] = 5
print(the_array)




[5. 5. 5. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
buckets = [5] * 10
print(buckets)




[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [21]:
l = []
for i in range(20,21,2):
    l.append(i)
for x in range(35,51,7):
    l.append(x)
print(l)


l = list(range(20,21,2)) + list(range(35,51,7))
print(l)




[20, 35, 42, 49]
[20, 35, 42, 49]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a = a + b
print(a)


[5 7 9]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [30]:
import pandas as pd


In [31]:
import pandas as pd

df=pd.DataFrame([['1/1/2001',1,21,1200],['1/1/2001',1,22,1000],['1/1/2001',1,23,1500],['2/1/2001',1,21,300],['2/1/2001',2,22,200],['3/1/2001',3,21,400],['4/1/2001',3,22,500]],columns=('Date','Id','Product','Sales'))

df['Id_Prod'] = df['Id'].astype(str).str.cat(df['Product'].astype(str), sep='_')

df.pivot(index='Date',columns='Id_Prod',values='Sales')




Id_Prod     1_21    1_22    1_23   2_22   3_21   3_22
Date                                                 
1/1/2001  1200.0  1000.0  1500.0    NaN    NaN    NaN
2/1/2001   300.0     NaN     NaN  200.0    NaN    NaN
3/1/2001     NaN     NaN     NaN    NaN  400.0    NaN
4/1/2001     NaN     NaN     NaN    NaN    NaN  500.0

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [35]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]